### ISSUE TITLE
Clone request

### ISSUE THREAD

**Issue by sidssn** [UKHomeOffice/acp-tf-s3#62]
Hello, is this module ready enough to be pulled as we want to upgrade our infrastructure with Terraform 0.12?

Thanks

**Comment by tasharnvb** [comment]
Hi, we're currently working on updating this module to be compatible with `0.12`. We have a PR open at the moment (https://github.com/UKHomeOffice/acp-tf-s3/pull/61) however we'll need to test this before we merge it to master and release a tag.

**Comment by sidssn** [comment]
Hello, is there an update on this or is this still under test?

**Comment by tasharnvb** [comment]
Hi sorry for the delay, we've updated the module to be compatible with Terraform 0.12 and have released a tag - https://github.com/UKHomeOffice/acp-tf-s3/releases
